---
services:
  slskd:
    build:
      context: ../../slskd
      dockerfile: Dockerfile
    container_name: slskd
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    env_file:
      - .env
    volumes:
      - ./data:/app
      - ./scripts:/app/scripts
    restart: always